In [3]:
import numpy as np

In [4]:
a = np.array ([0, 1, 2, 3, 4, 5])

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a.ndim

1

In [7]:
a.shape

(6L,)

We just created an array in a similar way to how we would create a list in Python.
However, NumPy arrays have additional information about the shape. In this case,
it is a one-dimensional array of five elements. No surprises so far.

We can now transform this array in to a 2D matrix:

In [8]:
b = a.reshape ((3, 2))

In [9]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(3L, 2L)

Ah-Ha! Eureka! ndim returns the dimensions of the array and shape returns the number and size of the sets.
A, which ia a one dimensional array, is a "straight line" of sequential numbers. In this regard, the ndim is 1 and the shape is 6L. Similiarly, b is two dimensional with three pairs of numbers for its shape!

In [12]:
c= a.reshape ((2, 3))

In [13]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c.ndim

2

In [18]:
c.shape

(2L, 3L)

In [19]:
b[1][0]=77

In this case, we have modified the value 2 to 77 in b, and we can immediately see
the same change reflected in a as well. Keep that in mind whenever you need a
true copy. The code is read as: 
# in array b, set 2, first value equals 77

In [20]:
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [21]:
a

array([ 0,  1, 77,  3,  4,  5])